version: "3.8"
services:
    # Database Server
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database
            
    database:
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: v3_myaccount
            MYSQL_USER: user1
            MYSQL_PASSWORD: secret
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data: ~